### ISSUE TITLE
Connection error with Spotify

### ISSUE THREAD

**Issue by thistehneisen** [bundit/kord#52]
As testing on kord.app, for some reason connection with Spotify fails. SoundCloud and YouTube works fine.

**Comment by bundit** [comment]
@thistehneisen 
Hey thanks for this. Does any error pop up after connecting? What happens when you click the sync icon in the profile view?

**Comment by thistehneisen** [comment]
From the Console, I see that this could be the issue:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.spotify.com/v1/me. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.spotify.com/v1/me/playlists?limit=50&offset=0. (Reason: CORS request did not succeed).
```
I'll note that I'm using Firefox Developers Edition

**Comment by bundit** [comment]
@thistehneisen 

I don't use Firefox Developers Edition but is it possible that an extension is blocking those requests? I have no issues with regular FireFox.
https://stackoverflow.com/a/56970532/11381730

**Comment by bundit** [comment]
This is working for me on Firefox Developers Edition so I'm closing this issue.

If you're still seeing this let me know and I will re-open this issue. Thanks
