### ISSUE TITLE
Can't link SoundCloud

### ISSUE THREAD

**Issue by SeriousM** [bundit/kord#70]
user: soundcloud.com/seriousm-1
GET: https://api.soundcloud.com/users/seriousm-1?client_id=e38841b15b2059a39f261df195dfb430
RESPONSE: 

```
{"code":400,"message":"Invalid user id: 'seriousm-1'","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"400 - Bad Request","errors":[{"error_message":"Invalid user id: 'seriousm-1'"}],"error":null}
```

Regarding to the soundcloud swagger page https://developers.soundcloud.com/docs/api/explorer/open-api an `userId` (numeric) is required to get a user with /users/{user_id}.

You could run a search with a limit to 1 in order to get the userid of an user based on his username:
`https://api.soundcloud.com/users?q=seriousm-1&limit=1&linked_partitioning=true&client_id=e38841b15b2059a39f261df195dfb430`
Then it's possible to query the user with the userid:
`https://api.soundcloud.com/users/4640955?client_id=e38841b15b2059a39f261df195dfb430`

using my id 4640955 on kord works btw. so kord is not broken entirely.

**Comment by bundit** [comment]
@SeriousM thanks for bringing this up. I'll be taking a look when I get a chance

**Comment by bundit** [comment]
@SeriousM been awhile but this fix has been merged and will be released tomorrow after some testing if you are still using kord :)

**Comment by bundit** [comment]
Soundcloud back online in production
